name = "1.19.4 Fabric Modpack"
author = "TomerGamerTV"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7828f1a31760dcacb7ce256cc659dd08d390c059be22361613a2432fcfec28de"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
