name = "1.19.4 Fabric Modpack"
author = "TomerGamerTV"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "859a16ac88ff5e4e1ca7d5aada3cf3f72793f493ddeea93aa799857c0e1cb5d9"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
